# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170427_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='courses/images', verbose_name='Imagem'),
        ),
    ]
