# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170427_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Atualizado em'),
        ),
    ]
